import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {Providers} from './GlobalRedux/provider'

const inter = Inter({ subsets: ["greek-ext"] });
import "./globals.css"
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import Navbar from "./components/Navbar/Navbar";
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>    
     
      {/* <script  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDPrIVGNbhIVuvl0pnlgy5mVm-3gIS4iCE&libraries=places&callback=initMap" async defer></script> */}
      </head>
      <body className={inter.className}>
         <Navbar />
        <Providers >
        {children}
        </Providers>
       
      </body>

    </html>
  );
}
